name: Bug report
description: Create a report to help us improve

labels:
  - bug
assignees:
  - nekofar

body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here.

  - type: textarea
    attributes:
      label: Steps to reproduce the behavior
      description: List the steps to reproduce the behavior, including any necessary environment details.
      placeholder: List the steps to reproduce here.

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior here.

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
      placeholder: Add any relevant screenshots here.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Add any additional context here.
